# Generated by Django 4.1.4 on 2023-01-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decricao', models.CharField(max_length=400, verbose_name='Descrição')),
                ('refeicao', models.IntegerField()),
            ],
        ),
    ]
