# Generated by Django 4.1.4 on 2023-01-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='almocoVeg',
            field=models.ManyToManyField(blank=True, related_name='Vegtarde', to='refeicao.componente'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='jantarVeg',
            field=models.ManyToManyField(blank=True, related_name='Vegnoite', to='refeicao.componente'),
        ),
    ]
