# Generated by Django 4.1.4 on 2023-01-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0003_cardapio_almocoveg_cardapio_jantarveg'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='cardapio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='refeicao.cardapio'),
            preserve_default=False,
        ),
    ]
