# Generated by Django 4.1.4 on 2023-01-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0004_comentario_cardapio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='almoco',
            field=models.ManyToManyField(blank=True, related_name='tarde', to='refeicao.componente', verbose_name='Almoço'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='data',
            field=models.DateField(unique=True),
        ),
    ]
